---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data
```{r}
dataFile <- unz(description = "activity.zip", filename = "activity.csv")
activityData <- read.table(file = dataFile, sep = ",", header = TRUE, na.strings = "NA")
activityData$date <- as.Date(activityData$date, format = "%Y-%m-%d")
head(activityData)
str(activityData)
xtabs(steps ~ date, data = activityData)
```

## What is mean total number of steps taken per day?

```{r}
plot(xtabs(steps ~ date, data = activityData), type = "h", ylab = "Steps", xlab = "Date")
mean(xtabs(steps ~ date, data = activityData))
median(xtabs(steps ~ date, data = activityData))
```

## What is the average daily activity pattern?
```{r}
library(reshape2)
actMelt <- melt(activityData, id = c("date", "interval"), measure.vars = c("steps"))
intervalMeans <- dcast(actMelt, interval ~ variable, mean, na.rm = TRUE)
plot(steps ~ interval, data = intervalMeans, type = "l")
max(intervalMeans$steps)
intervalMeans[intervalMeans$steps == max(intervalMeans$steps),]
```


## Imputing missing values

Using the floor function as step data should be in whole numbers

## Are there differences in activity patterns between weekdays and weekends?
weekdays(unique(activityData$date)